name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: |
          docker login -u Anonymes-User -p ${{ secrets.GITHUB_TOKEN }} 
          docker build . -t ghcr.io/Anonymes-User/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
      
      
      
      
      #  uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: ghcr.io/${{ github.repository }}